# Generated by Django 4.1.2 on 2022-11-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="headerposts", old_name="lt", new_name="feature_1",
        ),
        migrations.RenameField(
            model_name="headerposts", old_name="rt", new_name="feature_2",
        ),
        migrations.RenameField(
            model_name="headerposts", old_name="rbl", new_name="feature_3",
        ),
        migrations.RemoveField(model_name="headerposts", name="rbr",),
    ]
