# Generated by Django 4.1.2 on 2022-11-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_rename_lt_headerposts_feature_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="headerposts", old_name="feature_1", new_name="header_left",
        ),
        migrations.RenameField(
            model_name="headerposts",
            old_name="feature_3",
            new_name="header_right_bottom_left",
        ),
        migrations.RenameField(
            model_name="headerposts", old_name="feature_2", new_name="header_right_top",
        ),
        migrations.AddField(
            model_name="headerposts",
            name="header_right_bottom_right",
            field=models.IntegerField(default=4),
        ),
    ]
