# Generated by Django 4.1.2 on 2022-12-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rec_posts",
            field=models.CharField(default="1-2-3", max_length=250),
        ),
    ]
