# Generated by Django 4.1.2 on 2022-12-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("education", "Education"),
                    ("science-and-technology", "Science and Tech"),
                    ("finance", "Finance"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
