# Generated by Django 4.1.2 on 2022-12-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_category_post_cat"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="cat",),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.category",
            ),
        ),
    ]
