# Generated by Django 4.1.2 on 2022-12-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_remove_post_cat_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("education", "Education"),
                    ("science-and-technology", "Science and Tech"),
                    ("finance", "Finance"),
                ],
                default="education",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(name="Category",),
    ]
