# Generated by Django 4.1.2 on 2022-12-20 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0011_alter_post_category_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="desc",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="user_like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="tag_post", to="posts.tag"
            ),
        ),
    ]
