# Generated by Django 4.1.2 on 2022-12-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_post_desc_alter_post_likes_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="keywords",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
